import os
from dotenv import load_dotenv
from implicit_collaborative_recommender_systyem import ImplicitCollaborativeRecommenderSystem

load_dotenv()

URI = os.getenv('URI')

ImplicitCollaborativeRecommenderSystem.set_URI(URI)
ImplicitCollaborativeRecommenderSystem.implict_collaborative_recommender_system()
ImplicitCollaborativeRecommenderSystem.update_recs()