name: Basic Recommender System

on: 
    schedule:
    - cron: '0 0 * * 5'  # Executa todas as segundas-feiras às 00:00 UTC
jobs:
  run_function:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2
      
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'  # Escolha a versão do Python
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Se houver um arquivo de requisitos
        
    - name: Executar função
      run: |
        python src/index.py  # Substitua com o comando para executar sua função
