name: Phrases Recommender System

on: 
  schedule:
    - cron: '0 0 * * 5'  # Executes every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  run_function:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'  # Choose the Python version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # Allow failure
        
    - name: Install Windows-specific dependencies
      if: runner.os == 'Windows'
      run: |
        pip install pywin32
        
    - name: Execute function
      env:
        URI: ${{ secrets.MONGO_DB_BABYNAMES_SECRET }}
      run: |
        python src/index_phrases.py  # Replace with your function command